# Generated by Django 5.2.17 on 2026-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_profile_session_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(db_index=True, max_length=80)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('class_teacher', 'Class Teacher'), ('catalyst_member', 'Catalyst Member'), ('office', 'Office'), ('academic_supervisor', 'Academic Supervisor')], max_length=32)),
                ('field_key', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('module_key', 'role', 'field_key')},
            },
        ),
    ]
